/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author super
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        btnTb_NewFile = new javax.swing.JButton();
        btnTb_OpenFile = new javax.swing.JButton();
        btnTb_Save = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnTb_Cut = new javax.swing.JButton();
        btnTb_Copy = new javax.swing.JButton();
        btnTb_Paste = new javax.swing.JButton();
        btnTb_Find = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnTb_ChangeFont = new javax.swing.JButton();
        btnTb_CatalogFont = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnTb_Info = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnTb_Exit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnBtnNew = new javax.swing.JMenuItem();
        mnBtnOpen = new javax.swing.JMenuItem();
        mnBtnSave = new javax.swing.JMenuItem();
        mnBtnSaveAs = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnBtnExit = new javax.swing.JMenuItem();
        mnEdit = new javax.swing.JMenu();
        mnBtnCopy = new javax.swing.JMenuItem();
        mnBTnPaste = new javax.swing.JMenuItem();
        mnBtnCut = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnBtnFind = new javax.swing.JMenuItem();
        mnFormat = new javax.swing.JMenu();
        mnBtnFontType = new javax.swing.JMenuItem();
        mnBtnFontColor = new javax.swing.JMenuItem();
        mnBtnWorWrap = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mnBtnHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        btnTb_NewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/new.png"))); // NOI18N
        btnTb_NewFile.setFocusable(false);
        btnTb_NewFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_NewFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_NewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_NewFileActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_NewFile);

        btnTb_OpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/open.png"))); // NOI18N
        btnTb_OpenFile.setFocusable(false);
        btnTb_OpenFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_OpenFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_OpenFileActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_OpenFile);

        btnTb_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        btnTb_Save.setFocusable(false);
        btnTb_Save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_Save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_SaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_Save);
        jToolBar1.add(jSeparator1);

        btnTb_Cut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cut.png"))); // NOI18N
        btnTb_Cut.setFocusable(false);
        btnTb_Cut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_Cut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_Cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_CutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_Cut);

        btnTb_Copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/copy.png"))); // NOI18N
        btnTb_Copy.setFocusable(false);
        btnTb_Copy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_Copy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_Copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_CopyActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_Copy);

        btnTb_Paste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paste.png"))); // NOI18N
        btnTb_Paste.setFocusable(false);
        btnTb_Paste.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_Paste.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_PasteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_Paste);

        btnTb_Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/find.png"))); // NOI18N
        btnTb_Find.setFocusable(false);
        btnTb_Find.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_Find.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_FindActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_Find);
        jToolBar1.add(jSeparator3);

        btnTb_ChangeFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/font.png"))); // NOI18N
        btnTb_ChangeFont.setFocusable(false);
        btnTb_ChangeFont.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_ChangeFont.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_ChangeFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_ChangeFontActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_ChangeFont);

        btnTb_CatalogFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/folder_palette.png"))); // NOI18N
        btnTb_CatalogFont.setFocusable(false);
        btnTb_CatalogFont.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_CatalogFont.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_CatalogFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_CatalogFontActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_CatalogFont);
        jToolBar1.add(jSeparator4);

        btnTb_Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/help_about.png"))); // NOI18N
        btnTb_Info.setFocusable(false);
        btnTb_Info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_Info.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_InfoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_Info);
        jToolBar1.add(jSeparator5);

        btnTb_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/door_out.png"))); // NOI18N
        btnTb_Exit.setFocusable(false);
        btnTb_Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTb_Exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTb_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTb_ExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTb_Exit);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        mnFile.setText("File");

        mnBtnNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/new.png"))); // NOI18N
        mnBtnNew.setText("New File");
        mnFile.add(mnBtnNew);

        mnBtnOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/open.png"))); // NOI18N
        mnBtnOpen.setText("Open File");
        mnFile.add(mnBtnOpen);

        mnBtnSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        mnBtnSave.setText("Save");
        mnFile.add(mnBtnSave);

        mnBtnSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/saveAsText@3x.png"))); // NOI18N
        mnBtnSaveAs.setText("Save As...");
        mnFile.add(mnBtnSaveAs);
        mnFile.add(jSeparator6);

        mnBtnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/new.png"))); // NOI18N
        mnBtnExit.setText("Exit");
        mnFile.add(mnBtnExit);

        jMenuBar1.add(mnFile);

        mnEdit.setText("Edit");

        mnBtnCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/copy.png"))); // NOI18N
        mnBtnCopy.setText("Copy");
        mnEdit.add(mnBtnCopy);

        mnBTnPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBTnPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/paste.png"))); // NOI18N
        mnBTnPaste.setText("Paste");
        mnEdit.add(mnBTnPaste);

        mnBtnCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cut.png"))); // NOI18N
        mnBtnCut.setText("Cut");
        mnEdit.add(mnBtnCut);
        mnEdit.add(jSeparator7);

        mnBtnFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/find.png"))); // NOI18N
        mnBtnFind.setText("Find");
        mnEdit.add(mnBtnFind);

        jMenuBar1.add(mnEdit);

        mnFormat.setText("Format");

        mnBtnFontType.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnFontType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/font.png"))); // NOI18N
        mnBtnFontType.setText("Font type");
        mnBtnFontType.setRolloverEnabled(true);
        mnFormat.add(mnBtnFontType);

        mnBtnFontColor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnFontColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/folder_palette.png"))); // NOI18N
        mnBtnFontColor.setText("Font Color");
        mnFormat.add(mnBtnFontColor);

        mnBtnWorWrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/T_WordWrap_Sm_N@3x.png"))); // NOI18N
        mnBtnWorWrap.setText("Word Wrap");
        mnFormat.add(mnBtnWorWrap);

        jMenuBar1.add(mnFormat);

        mnHelp.setText("Help");

        mnBtnHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnBtnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/help_about.png"))); // NOI18N
        mnBtnHelp.setText("About This");
        mnHelp.add(mnBtnHelp);

        jMenuBar1.add(mnHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTb_NewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_NewFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_NewFileActionPerformed

    private void btnTb_OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_OpenFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_OpenFileActionPerformed

    private void btnTb_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_SaveActionPerformed

    private void btnTb_CutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_CutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_CutActionPerformed

    private void btnTb_CopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_CopyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_CopyActionPerformed

    private void btnTb_PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_PasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_PasteActionPerformed

    private void btnTb_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_FindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_FindActionPerformed

    private void btnTb_ChangeFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_ChangeFontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_ChangeFontActionPerformed

    private void btnTb_CatalogFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_CatalogFontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_CatalogFontActionPerformed

    private void btnTb_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_InfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_InfoActionPerformed

    private void btnTb_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTb_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTb_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }
    
    public void showApp() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTb_CatalogFont;
    private javax.swing.JButton btnTb_ChangeFont;
    private javax.swing.JButton btnTb_Copy;
    private javax.swing.JButton btnTb_Cut;
    private javax.swing.JButton btnTb_Exit;
    private javax.swing.JButton btnTb_Find;
    private javax.swing.JButton btnTb_Info;
    private javax.swing.JButton btnTb_NewFile;
    private javax.swing.JButton btnTb_OpenFile;
    private javax.swing.JButton btnTb_Paste;
    private javax.swing.JButton btnTb_Save;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnBTnPaste;
    private javax.swing.JMenuItem mnBtnCopy;
    private javax.swing.JMenuItem mnBtnCut;
    private javax.swing.JMenuItem mnBtnExit;
    private javax.swing.JMenuItem mnBtnFind;
    private javax.swing.JMenuItem mnBtnFontColor;
    private javax.swing.JMenuItem mnBtnFontType;
    private javax.swing.JMenuItem mnBtnHelp;
    private javax.swing.JMenuItem mnBtnNew;
    private javax.swing.JMenuItem mnBtnOpen;
    private javax.swing.JMenuItem mnBtnSave;
    private javax.swing.JMenuItem mnBtnSaveAs;
    private javax.swing.JMenuItem mnBtnWorWrap;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnFormat;
    private javax.swing.JMenu mnHelp;
    // End of variables declaration//GEN-END:variables
}
